name: Test setup-ruby with TruffleRuby
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu', 'macos' ]
        ruby: [ '2.6.x', 'truffleruby-19.2.0' ]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@master
    - uses: eregon/setup-ruby@truffleruby
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: ruby -v
    - run: ruby -ropen-uri -e 'puts open("https://rubygems.org/") { |f| f.read(1024) }'
