name: Test ruby/setup-ruby with TruffleRuby
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu, macos ]
        ruby: [ 2.6, truffleruby ]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: ruby -v
    - run: ruby -ropen-uri -e 'puts open("https://rubygems.org/") { |f| f.read(1024) }'
