name: Test
on:
  push:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        ruby: [ 2.5, jruby ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: ruby -v

    - run: cat $(ruby -e 'puts RbConfig::CONFIG["bindir"]')/rake
      shell: bash
    - run: cat $(ruby -e 'puts RbConfig::CONFIG["bindir"]')/rake.bat
      shell: bash

    - run: bundle install

    - run: cat $(ruby -e 'puts RbConfig::CONFIG["bindir"]')/rake
      shell: bash
    - run: cat $(ruby -e 'puts RbConfig::CONFIG["bindir"]')/rake.bat
      shell: bash

    - run: bundle exec rake
