name: Test
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, macos, windows ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - run: echo "C:\msys64\usr\bin" >> $GITHUB_PATH
        shell: bash

      - uses: actions/cache@v2
        with:
          path: top/foo
          key: ${{ runner.os }}-debug-cache1

      - run: ls -l
        shell: bash

      - name: Generate files
        run: |
          mkdir -p top/foo
          echo hello > top/foo/bar.txt
        shell: bash
