name: Test ruby/setup-ruby
on: [push, workflow_dispatch]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-10.15, macos-11, macos-12, windows-2019, windows-2022 ]
        ruby: [ 3.2 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: eregon/setup-ruby@consider-different-toolcache-self-hosted
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
