name: Test ruby/setup-ruby
on: [push, workflow_dispatch]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
        ruby: [ 2.5 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@master
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: none
    - run: ruby -v
