name: Test ruby/setup-ruby
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]
        ruby: [ truffleruby, truffleruby-head ]
    runs-on: ${{ matrix.os }}
    env:
      TRUFFLERUBYOPT: "--vm.XX:+PrintGC --vm.XX:+VerboseGC --vm.XX:+PrintGCSummary --experimental-options --engine.TraceCompilation"
    steps:
    - uses: actions/checkout@v2

    # No bundle lock before, mem
    - run: rm -rf vendor/bundle Gemfile.lock
    - uses: eregon/setup-ruby@debug-truffleruby-bundler-oom
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: rm -rf vendor/bundle Gemfile.lock
    - uses: eregon/setup-ruby@debug-truffleruby-bundler-oom
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: rm -rf vendor/bundle Gemfile.lock
    - uses: eregon/setup-ruby@debug-truffleruby-bundler-oom
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: rm -rf vendor/bundle Gemfile.lock
    - uses: eregon/setup-ruby@debug-truffleruby-bundler-oom
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: rm -rf vendor/bundle Gemfile.lock
    - uses: eregon/setup-ruby@debug-truffleruby-bundler-oom
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true


    - run: rm -rf vendor/bundle Gemfile.lock
    - uses: eregon/setup-ruby@debug-truffleruby-bundler-oom
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: rm -rf vendor/bundle Gemfile.lock
    - uses: eregon/setup-ruby@debug-truffleruby-bundler-oom
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: rm -rf vendor/bundle Gemfile.lock
    - uses: eregon/setup-ruby@debug-truffleruby-bundler-oom
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: rm -rf vendor/bundle Gemfile.lock
    - uses: eregon/setup-ruby@debug-truffleruby-bundler-oom
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: rm -rf vendor/bundle Gemfile.lock
    - uses: eregon/setup-ruby@debug-truffleruby-bundler-oom
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
