name: Test
on:
  push:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        ruby: [ 2.5, jruby ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - run: echo $env:PATH
    - run: echo $PATH
      shell: bash

    - uses: ruby/setup-ruby@fix-jruby
      with:
        ruby-version: ${{ matrix.ruby }}

    - run: echo $env:path
    - run: echo $PATH
      shell: bash
    - run: echo $PATHEXT
      shell: bash

    - run: cp C:\Users\runneradmin\.rubies\jruby-9.2.9.0\bin\jruby.sh C:\Users\runneradmin\.rubies\jruby-9.2.9.0\bin\jruby
      if: matrix.ruby == 'jruby'
    - run: cp C:\Users\runneradmin\.rubies\jruby-9.2.9.0\bin\jruby.sh C:\Users\runneradmin\.rubies\jruby-9.2.9.0\bin\ruby
      if: matrix.ruby == 'jruby'

    - run: ruby -v
    - run: ruby -v
      shell: bash

    - run: ruby -e 'puts RbConfig::CONFIG["bindir"]'
      shell: bash
    - run: cat $(ruby -e 'puts RbConfig::CONFIG["bindir"]')/rake
      shell: bash
    # - run: cat $(ruby -e 'puts RbConfig::CONFIG["bindir"]')/rake.bat
    #   shell: bash

    - run: bundle install

    - run: cat $(ruby -e 'puts RbConfig::CONFIG["bindir"]')/rake
      shell: bash
    # - run: cat $(ruby -e 'puts RbConfig::CONFIG["bindir"]')/rake.bat
    #   shell: bash

    - run: bundle exec rake
