name: Test ruby/setup-ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      uses: softprops/action-gh-release@v1
      id: create_release
      with:
        tag_name: testtag
        draft: true
        prerelease: false
        body: body

    - run: 'echo hello > foo.txt'
    - name: Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: testtag
        files: foo.txt
