name: Test setup-ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: eregon/setup-ruby@truffleruby
      with:
        ruby-version: 'truffleruby-19.2.0'
    - run: |
        ruby -v
        ruby -ropen-uri -e 'puts open("https://rubygems.org/") { |f| f.read(1024) }'
