name: Test
on:
  push:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        ruby: [ 2.5, jruby ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - run: echo $env:PATH
    - run: echo $PATH
      shell: bash

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - run: echo $env:path
    - run: echo $PATH
      shell: bash
    - run: echo $PATHEXT
      shell: bash

    - run: ruby -v
    - run: ruby -v
      shell: bash

    - run: ruby -e 'puts RbConfig::CONFIG[%{bindir}]'
      shell: bash
    - run: cat $(ruby -e 'puts RbConfig::CONFIG[%{bindir}]')/rake
      shell: bash
    - run: cat $(ruby -e 'puts RbConfig::CONFIG[%{bindir}]')/rake.bat
      shell: bash
      if: matrix.ruby == 'jruby'

    - run: gem install bundler
    - run: bundle --version

    - run: bundle install

    - run: cat $(ruby -e 'puts RbConfig::CONFIG[%{bindir}]')/rake
      shell: bash
    - run: cat $(ruby -e 'puts RbConfig::CONFIG[%{bindir}]')/rake.bat
      shell: bash
      # if: matrix.ruby == 'jruby'

    - run: bundle exec rake --version
    - run: bundle exec rake
