name: Test ruby/setup-ruby
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu ]
        ruby: [ truffleruby, truffleruby-head ]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: bundle config --local path vendor/bundle

    - run: rm -rf vendor/bundle
    - run: bundle install --jobs 4
    - run: rm -rf vendor/bundle
    - run: bundle install --jobs 4
    - run: rm -rf vendor/bundle
    - run: bundle install --jobs 4
    - run: rm -rf vendor/bundle
    - run: bundle install --jobs 4
    - run: rm -rf vendor/bundle
    - run: bundle install --jobs 4

    - run: rm -rf vendor/bundle
    - run: bundle install --jobs 4
    - run: rm -rf vendor/bundle
    - run: bundle install --jobs 4
    - run: rm -rf vendor/bundle
    - run: bundle install --jobs 4
    - run: rm -rf vendor/bundle
    - run: bundle install --jobs 4
    - run: rm -rf vendor/bundle
    - run: bundle install --jobs 4
