name: Test ruby/setup-ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v3

    - run: gh release create --draft vbar --title vbar --notes "my body"
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}

    - run: echo hello > foo.txt
    - run: gh release upload vbar foo.txt
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}

    - run: gh release edit vbar --draft=false
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
