name: Test ruby/setup-ruby
on: [push, workflow_dispatch]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, ubuntu-22.04 ]
        ruby: [ '3.0' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1.138.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: which -a mkdir
    - run: ruby -e 'p RbConfig::CONFIG["MKDIR_P"]'
